name: comments_remover
description: A command-line tool to remove comments from Dart files in a Flutter project.
version: 1.0.2
repository: https://github.com/benouarAbdou/comments_remover_flutter_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0

executables:
  comments_remover: main  # Maps "comments_remover" command to bin/main.dart