name: comments_remover
description: A Dart package to remove single-line (//) and multi-line (/* */) comments from Dart files in a Flutter project.
version: 1.0.0
repository: https://github.com/benouarAbdou/comments_remover_flutter_package

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0  # For file path manipulation

dev_dependencies:
  test: ^1.16.0